FROM gridappsd/gridappsd_base
RUN printenv
WORKDIR /working

RUN git clone https://github.com/tdtalbot/GOSS-GridAPPS-D -b master --single-branch

WORKDIR /working/GOSS-GridAPPS-D/gov.pnnl.goss.gridappsd

RUN ../gradlew export
RUN cp generated/distributions/executable/run.bnd.jar ${GRIDAPPSD}/lib

WORKDIR /working/GOSS-GridAPPS-D
RUN mkdir -p ${GRIDAPPSD}/scripts/
#cp applications/python/fncs_goss_bridge.py ~/gridappsd_project/builds/scripts/
#cp applications/etc/zipload_schedule.player ~/gridappsd_project/builds/scripts/

#cp ~/gridappsd_project/sources/fncs/python/fncs.py ~/gridappsd_project/builds/scripts/
RUN cp -R ./applications ${GRIDAPPSD}
RUN cp -R ./services ${GRIDAPPSD}

EXPOSE 61614

WORKDIR ${GRIDAPPSD}
COPY ./conf ${GRIDAPPSD}/conf
COPY ./run-goss-test.sh ${GRIDAPPSD}
RUN chmod +x run-goss-test.sh
#CMD [java", "-jar", "generated/distributions/executable/run.bnd.jar"]
#CMD ["ping", "mysql", "-c", "5"]
CMD ["./run-goss-test.sh"]
#java", "-jar", "generated/distributions/executable/run.bnd.jar"]
