FROM node:boron

WORKDIR /viz

RUN npm install -g typescript
RUN npm install -g typings
RUN npm install -g webpack

RUN git clone https://github.com/GRIDAPPSD/viz -b master --single-branch

WORKDIR /viz/viz

RUN npm install


ENV VIZ_PORT=8082
ENV PORT=${VIZ_PORT}
EXPOSE ${VIZ_PORT}
RUN printenv
RUN ls -la
RUN which node
RUN echo $PATH
CMD ["npm", "start"] 

