FROM node:boron

WORKDIR /viz

RUN npm install -g typescript
RUN npm install -g typings
RUN npm install -g webpack

#RUN git clone https://github.com/GRIDAPPSD/viz -b master --single-branch
RUN git clone https://github.com/craig8/viz -b dockerized --single-branch

WORKDIR /viz/viz

RUN npm install
RUN webpack

ENV VIZ_PORT=8082
ENV PORT=${VIZ_PORT}
EXPOSE ${VIZ_PORT}

CMD ["npm", "start"] 

